// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_DataAccess.Data;

#nullable disable

namespace ShopProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shop_Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 100,
                            Name = "Ecrane"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 100,
                            Name = "Capace Spate"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 100,
                            Name = "Acumulatori"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 10,
                            Name = "Programare Reparatii"
                        });
                });

            modelBuilder.Entity("Shop_Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CodProdus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Culoare")
                        .HasColumnType("longtext");

                    b.Property<string>("Descriere")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("ListPrice")
                        .HasColumnType("double");

                    b.Property<string>("ModelCompatibil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nume")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<double>("Price3")
                        .HasColumnType("double");

                    b.Property<string>("Producator")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CodProdus = "GH82-20528A",
                            Culoare = "Aura Black",
                            Descriere = "Capac baterie original, Service Pack pentru Samsung Galaxy Note 10",
                            ImageUrl = "",
                            ListPrice = 180.0,
                            ModelCompatibil = "N970",
                            Nume = "Capac spate",
                            Price = 170.0,
                            Price3 = 160.0,
                            Producator = "SAMSUNG"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CodProdus = "GH82-20528C",
                            Culoare = "Aura Glow",
                            Descriere = "Capac baterie original, Service Pack pentru Samsung Galaxy Note 10",
                            ImageUrl = "",
                            ListPrice = 180.0,
                            ModelCompatibil = "N970",
                            Nume = "Capac spate",
                            Price = 170.0,
                            Price3 = 160.0,
                            Producator = "SAMSUNG"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CodProdus = "GH82-20528B",
                            Culoare = "Aura White",
                            Descriere = "Capac baterie original, Service Pack pentru Samsung Galaxy Note 10",
                            ImageUrl = "",
                            ListPrice = 180.0,
                            ModelCompatibil = "N970",
                            Nume = "Capac spate",
                            Price = 170.0,
                            Price3 = 160.0,
                            Producator = "SAMSUNG"
                        });
                });

            modelBuilder.Entity("Shop_Models.Models.Product", b =>
                {
                    b.HasOne("Shop_Models.Models.Category", "MyProprety")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyProprety");
                });
#pragma warning restore 612, 618
        }
    }
}
